name: Add File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File name'
        default: 'newfile'
        required: true
        type: string
        
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create ${{ inputs.file }}
      run: touch ${{ inputs.file }}
