name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove peripheral files
        run: rm README.md

      - uses: actions/checkout@v3
      - name: Remove peripheral directories
        run: rm -rf .github

      - uses: actions/checkout@v3
      - name: Create archive
        run: zip -r rpiwpx pkg rpi-wpx LICENSE install.sh

      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: rpiwpx
          path: rpiwpx.zip
