name: Remove File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File name'
        default: 'file'
        required: true
        type: string
        
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Remove ${{ inputs.file }}
      run: rm ${{ inputs.file }}
